services:
  rabbitmq_eco:
    image: rabbitmq:management
    container_name: rabbitmq_eco
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - app_network
  db_proyect:
    image: mysql:9.2.0
    environment:
      MYSQL_DATABASE: 'proyecto'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network 
networks:
  app_network:
    driver: bridge
volumes:
  mysql_data:
